---
title: "Research and professional experience"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

### Education: 

MPH Epidemiology, Certiifcate in Applied Biostatistics - 
Columbia University, Mailman School of Public Health, NY, USA

Bachelor of Pharmacy, Pharmaceutical Sciences - 
Institute of CHemical Technology, Mumbai, India

## Academic and professional experience  {.tabset}

### Current projects

**Randomized Controlled trial for web based decision aid tools** 
**New York Presbyterian Hospital – Columbia University Irving Medical Center**
Graduate Research Assistant 

•	Analyzed data using SAS for over 6000 women at high risk for breast cancer in an ongoing Randomized Controlled Trial of web-based decision support tools for increased chemoprevention uptake. Leveraged analysis of 5 recruitment strategies, baseline characteristics and perceptions of women at high risk for breast cancer to improve the identification of high-risk women and increase yield of participation in cancer chemoprevention trials. 
 
•	Principal analysis of data involving 300 women enrolled in the trial to assess the association between exposure to decision support tools and change in decision quality measures.

•	Calculated Breast Cancer Risk Scores using the data retrieved from EHR and the BCSC source code for risk calculation.

•	Created abstracts, summary tables, reports, figures and text for external manuscript publication and presentation to the San Antonio Breast Cancer Symposium 2020, leading to the selection of the abstract for poster presentation at the symposium in December 2020.  

**Use of Hair Care Products containing phthalates among pregnant women: A Northern Manhattan intervention.** 
**Herbert Irving Comprehensive Cancer Center, Columbia University**	         	                                  
Research Assistant

•	Developed tools for the mixed methods study design including baseline and follow up questionnaires to assess the product use, eligibility and sociodemographic characteristics using Qualtrics. 

•	Employed the 7 Stage Precaution Adoption Process Model (PAPM) to develop questionnaires to measure the self-reported behavior changes and identify the participant’s PAPM stage at pre and post intervention, 1 month and 6 months timeline. 

•	Developed an educational intervention on harmful phthalate exposure using empirical evidence through rigorous literature review and created a semi-structured guide to facilitate focus group discussion. 

•	Facilitated registration of the study to clinicaltrials.gov. 

**Pharmacovigilance avtivities at Otsuka Pharmaceuticals**

Pharmacovigilance at Otsuka-
•	Assisted Otsuka’s Global Pharmacovigilance – Medical Safety team in Risk Management activities including evaluation of safety reports, signal management, Risk Management Plans (RMP). 
•	Responsible for the Epidemiology section of the RMP for Otsuka and collaborators’ products. 
•	Provided Epidemiology services to Otsuka Pharmaceutical as a part of the Otsuka Medical Advisory Committee to guide their post pandemic reopening plans.
•	Prepare a manuscript with an analysis of Gastrointestinal Cancer outcomes in HIV positive patients. 
•	Create summary tables, text for a competitive D43 training grant application that encourages bilateral scientific exchange in oncology between Columbia University and South African University of Witwatersrand.


### Research Interests

I am interested in studying the pharmacoepidemiologic methods involved in studying the usage, safety and efficacy of drugs administered during critical windows of susceptibility. 

### Publications and Presentations

“Oral Cancer awareness among students from Mumbai University” in the International Journal of Basic & Clinical Pharmacology. 
[DOI] (http://dx.doi.org/10.18203/2319-2003.ijbcp20182667)


